    %% Model fitting function
    function model = twoClassSVM(data, labels, hyperparams)
    
        model = compact(fitcsvm(data, labels,'ShrinkagePeriod', ...
            hyperparams.ShrinkagePeriod,'Solver',hyperparams.Solver, ...
            'IterationLimit',hyperparams.IterationLimit,'Cost',...
            hyperparams.Cost,'ClassNames',hyperparams.ClassNames, ...
            'Verbose',hyperparams.Verbose));
            
    end